### ISSUE TITLE
PDFs können nicht generiert werden: Absoluter statt relativer Pfad wird benutzt

### ISSUE THREAD

**Issue by NikTheDusky** [CatoTH/antragsgruen#622]
Hi,

ich nochmal, neben #621 haben wir noch ein anderes Problem, es ist zurzeit keine Generierung von PDFs möglich.
Der Fehler äußert sich im app.log wie folgt:
`2022-01-27 11:16:38 [error][yii\base\ErrorException:2] yii\base\ErrorException: file_exists(): open_basedir restriction in effect. File(/web/std/page/files/logo.png) is not within the allowed path(s): (/var/www/:/tmp/:/usr/bin/) in /var/www/website/views/pdfLayouts/ByLDK.php:129`

Die Anwendung scheint hier auf `/web` im Root des Dateisystems statt im Root der Anwendung (was unter `/var/www/website/web` wäre) zugreifen zu wollen.
Zuerst gingen wir hier von einem Konfigurationsfehler aus, jedoch ist in der `config/config.json` nur eine Einstellung zu finden, die damit zu tun haben könnte: `"resourceBase": "\/web\/",`
Wir haben einmal versucht, resourceBase auf einen absoluten Pfad zu setzen oder ihn weiter zu relativieren, z.B. zu `./web/`, leider hat das auch nicht funktioniert (wahrscheinlich, weil es bei resourceBase um den Pfad geht, unter welchem die Seite nachher ausgeliefert wird?).
Danach habe ich noch einmal die Berechtigungen nachgeprüft, doch diese passen alle.

Mich wundert das Problem hier etwas, da es nach einem sehr trivialen Fehler aussieht.

**Comment by NikTheDusky** [comment]
@CatoTH Korrekt, die Option ist auf die Verzeichnisse gesetzt, die auch schon in der Fehlermeldung stehen. Soweit ich weiß, ist das aber rekursiv, sollte dann nicht komplett Antragsgrün mit einbezogen sein, wenn das unter `/var/www/` liegt?

**Comment by NikTheDusky** [comment]
@CatoTH Wir haben einmal die `open_basedir`-Konfiguration aus der PHP-Config entfernt, tatsächlich war nun eine PDF-Generation möglich. Nun gibt es aber ein anderes Problem beim Aufrufen von PDFs :/

```
2022-01-28 12:52:04 [error][yii\base\ErrorException:2] yii\base\ErrorException: Trying to access array offset on value of type null in /var/www/website/models/sectionTypes/Image.php:291
Stack trace:
#0 /var/www/website/models/sectionTypes/Image.php(291): yii\base\ErrorHandler->handleError()
#1 /var/www/website/models/sectionTypes/Image.php(331): app\models\sectionTypes\Image->printMotionToPDF()
#2 /var/www/website/views/amendment/LayoutHelper.php(98): app\models\sectionTypes\Image->printAmendmentToPDF()
#3 /var/www/website/views/amendment/LayoutHelper.php(137): app\views\amendment\LayoutHelper::printToPDF()
#4 /var/www/website/controllers/AmendmentController.php(64): app\views\amendment\LayoutHelper::createPdfTcpdf()
#5 [internal function]: app\controllers\AmendmentController->actionPdf()
#6 /var/www/website/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array()
#7 /var/www/website/vendor/yiisoft/yii2/base/Controller.php(181): yii\base\InlineAction->runWithParams()
#8 /var/www/website/vendor/yiisoft/yii2/base/Module.php(534): yii\base\Controller->runAction()
#9 /var/www/website/vendor/yiisoft/yii2/web/Application.php(104): yii\base\Module->runAction()
#10 /var/www/website/vendor/yiisoft/yii2/base/Application.php(392): yii\web\Application->handleRequest()
#11 /var/www/website/web/index.php(22): yii\base\Application->run()
#12 {main}
```

Das Problem tritt komischerweise nur bei Anträgen des Typs ÄA auf (Entschuldigt, ich habe keine Ahnung, was das bedeutet, ich bin kein Nutzer), wie unter `web/std/admin/list` zu sehen ist. Anträge ohne eine Zahl hinter dem Antragsnamen oder des Typs A funktionieren einwandfrei.
(Beispiel: `web/std/antragsname/19/pdf` ist defekt, `web/std/antragsname/pdf` funktioniert).

**Comment by CatoTH** [comment]
Das ganze scheint dann aufzutreten, wenn eine sehr unübliche Kombination aus Einstellungen angewendet wird - wenn man Änderungsanträge für Bilder zulässt. Das wird eigentlich gar nicht unterstützt, lässt sich aber wohl einstellen und führt dann zu diversen Problemen. Für diesen konkreten Fall hab ich jetzt einmal hier einen Workaround geschrieben, den könnt ihr ja ggf. einspielen: https://github.com/CatoTH/antragsgruen/commit/0a05e26c71b223536b915e7102c09579ffe36ec1 . Dann wird das PDF gerendert, wenn auch ohne das Bild.

**Comment by NikTheDusky** [comment]
Vielen Dank für die schnelle Antwort! Wir testen dann ggf. einmal die Version an 0a05e26c71b223536b915e7102c09579ffe36ec1 und geben dann Rückmeldung.
