### ISSUE TITLE
Bug: yii cli not working, dependencies missing

### ISSUE THREAD

**Issue by lukas-staab** [CatoTH/antragsgruen#725]
In a fresh downloaded release the cli does not work. It seems there are some dev dependencies missing / not delivered in the vendor file. Here some excerpt from the stack trace
```
$ php8.0 yii 
```
```
/var/www/antragsgruen-4.10.1/vendor/yiisoft/yii2/test/FixtureTrait.php): Failed to open stream: No such file or directory in /var/www/antragsgruen-4.10.1/vendor/yiisoft/yii2/BaseYii.php:293
Stack trace:
#0 /var/www/antragsgruen-4.10.1/vendor/yiisoft/yii2/BaseYii.php(293): yii\base\ErrorHandler->handleError()
#1 /var/www/antragsgruen-4.10.1/vendor/yiisoft/yii2/BaseYii.php(293): include()
#2 /var/www/antragsgruen-4.10.1/vendor/yiisoft/yii2/console/controllers/FixtureController.php(45): yii\BaseYii::autoload()
#3 /var/www/antragsgruen-4.10.1/vendor/yiisoft/yii2/BaseYii.php(293): include('...')
#4 [internal function]: yii\BaseYii::autoload()
#5 /var/www/antragsgruen-4.10.1/vendor/yiisoft/yii2/di/Container.php(507): ReflectionClass->__construct()
#6 /var/www/antragsgruen-4.10.1/vendor/yiisoft/yii2/di/Container.php(385): yii\di\Container->getDependencies()
#7 /var/www/antragsgruen-4.10.1/vendor/yiisoft/yii2/di/Container.php(170): yii\di\Container->build()
#8 /var/www/antragsgruen-4.10.1/vendor/yiisoft/yii2/BaseYii.php(345): yii\di\Container->get()
#9 /var/www/antragsgruen-4.10.1/vendor/yiisoft/yii2/base/Module.php(607): yii\BaseYii::createObject()
#10 /var/www/antragsgruen-4.10.1/vendor/yiisoft/yii2/console/controllers/HelpController.php(175): yii\base\Module->createController()
#11 [internal function]: yii\console\controllers\HelpController->yii\console\controllers\{closure}()
```

**Comment by lukas-staab** [comment]
With a fresh git clone it works fine, even with 

``` 
composer install --no-dev 
``` 
so this seems like an issue in the packaging process of the releases, not the code base itself.

**Comment by CatoTH** [comment]
Ok I'll have a look at it this weekend. As the v4.11 release is close, I will probably fix it as part of that.
