### ISSUE TITLE
Unhandled excpetion when uploading PDF as image

### ISSUE THREAD

**Issue by svenseeberg** [CatoTH/antragsgruen#758]
When uploading a motion (`POST /MYEVENT/motion/create?agendaItemId=MYID`) and accidentally selecting an PDF file instead of an image, an unhandled excpetion occurs:

```
2023-01-24 20:48:17 [91.16.121.60][31825][0rhdfcd6tpreuluip81bhl26qd][error][yii\base\ErrorException:2] yii\base\ErrorException: getimagesize(/var/www/runtime/tmp/pdf-63d03601de708.png): Failed to open stream: No such file or directory in /var/www/models/sectionTypes/Image.php:202
Stack trace:
#0 [internal function]: yii\base\ErrorHandler->handleError()
#1 /var/www/models/sectionTypes/Image.php(202): getimagesize()
#2 /var/www/models/forms/MotionEditForm.php(151): app\models\sectionTypes\Image->setMotionData()
#3 /var/www/models/forms/MotionEditForm.php(258): app\models\forms\MotionEditForm->setAttributes()
#4 /var/www/controllers/MotionController.php(365): app\models\forms\MotionEditForm->createMotion()
#5 [internal function]: app\controllers\MotionController->actionCreate()
#6 /var/www/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array()
#7 /var/www/vendor/yiisoft/yii2/base/Controller.php(178): yii\base\InlineAction->runWithParams()
#8 /var/www/controllers/Base.php(142): yii\base\Controller->runAction()
#9 /var/www/vendor/yiisoft/yii2/base/Module.php(552): app\controllers\Base->runAction()
#10 /var/www/vendor/yiisoft/yii2/web/Application.php(103): yii\base\Module->runAction()
#11 /var/www/vendor/yiisoft/yii2/base/Application.php(384): yii\web\Application->handleRequest()
#12 /var/www/web/index.php(55): yii\base\Application->run()
#13 {main}
```

Users should be warned that PDFs cannot be uploaded. Only supported image files (PNG, JPG) can be uploaded.

**Comment by CatoTH** [comment]
Ich konnte das jetzt gerade nicht nachstellen... passiert das auf antragsgruen.de auf einer Seite? Mit welchem PDF?
An sich sollte es abgefangen werden, ein PDF hochzuladen, es wird dann halt nur die erste Seite in ein PNG umgewandelt. Das scheint hier jetzt nicht funktioniert zu haben...
