### ISSUE TITLE
pdfExportIntegFrame – behaviour change?

### ISSUE THREAD

**Issue by macwinnie** [CatoTH/antragsgruen#760]
Hi @CatoTH =)

was there any change in the expected behaviour for `pdfExportIntegFrame`? Updating to latest version gives me somehow the error, an associative array could not be assigned to the key `pdfExportIntegFrame` ... before, that setting worked well for us =D

```json
{
    ....
    "pdfExportIntegFrame": {
        "color": [
            100,
            0,
            80,
            10
        ],
        "lw": 0.05,
        "abs": true,
        "trd": 10,
        "trl": 10,
        "blu": 10,
        "blr": 10
    },
    ....
}
```

Thanks for having a look or giving me a hint on what changed =D
Best
macwinnie

**Comment by CatoTH** [comment]
Hi!
Hm, I wasn't really aware there could be arrays, too, not only integers. The following patch should fix this: https://github.com/CatoTH/antragsgruen/commit/db7b73c346daa24d6a027d4cab94dff3a86c4fe0

**Comment by macwinnie** [comment]
Hi =)

Hmm ... strange ... The type-casts were implemented quite a time ago ... but until the version 4.10.1 they did not have effects on our installation (after that version, the changes in GitHub Actions behavior had broken the automatic build of the `latest` version tag of the Docker container images we're using by ourselfs).

Additionally to the type cast of `pdfExportIntegFrame` in `models/settings/AntragsgruenApp.php` I now encountered related problems with `forceLogin` and `managedUserAccounts` in `models/settings/Consultation.php`: Not having defined anything related to them in our `config.json`, there was an error thrown for both like that:

```
2023-02-06 09:54:12 [127.0.0.1][-][-][error][TypeError] TypeError: Cannot assign null to property app\models\settings\Consultation::$managedUserAccounts of type bool in /var/www/html/models/settings/JsonC
onfigTrait.php:75                                                                                                                                                                                           
Stack trace:                                                                                                                                                                                                
#0 /var/www/html/models/settings/JsonConfigTrait.php(14): app\models\settings\Consultation->setPropertiesFromJSON('{\n    "maintena...')                                                                    
#1 /var/www/html/models/db/Consultation.php(424): app\models\settings\Consultation->__construct('{\n    "maintena...')                                                                                      
#2 /var/www/html/controllers/Base.php(539): app\models\db\Consultation->getSettings()                                                                                                                       
#3 /var/www/html/controllers/Base.php(82): app\controllers\Base->loadConsultation('std', 'mv41')                                                                                                            
#4 /var/www/html/controllers/ConsultationController.php(45): app\controllers\Base->beforeAction(Object(yii\base\InlineAction))                                                                              
#5 /var/www/html/vendor/yiisoft/yii2/base/Controller.php(176): app\controllers\ConsultationController->beforeAction(Object(yii\base\InlineAction))                                                          
#6 /var/www/html/controllers/Base.php(148): yii\base\Controller->runAction('home', Array)                                                                                                                   
#7 /var/www/html/vendor/yiisoft/yii2/base/Module.php(552): app\controllers\Base->runAction('home', Array)                                                                                                   
#8 /var/www/html/vendor/yiisoft/yii2/web/Application.php(103): yii\base\Module->runAction('consultation/ho...', Array)                                                                                      
#9 /var/www/html/vendor/yiisoft/yii2/base/Application.php(384): yii\web\Application->handleRequest(Object(yii\web\Request))                                                                                 
#10 /var/www/html/web/index.php(52): yii\base\Application->run()                                                                                                                                            
#11 {main}
```

and 

```
2023-02-06 09:52:41 [127.0.0.1][-][-][error][TypeError] TypeError: Cannot assign null to property app\models\settings\Consultation::$forceLogin of type bool in /var/www/html/models/settings/JsonConfigTrai
t.php:75                                                                                                                                                                                                    
Stack trace:                                                                                                                                                                                                
#0 /var/www/html/models/settings/JsonConfigTrait.php(14): app\models\settings\Consultation->setPropertiesFromJSON('{\n    "maintena...')                                                                    
#1 /var/www/html/models/db/Consultation.php(424): app\models\settings\Consultation->__construct('{\n    "maintena...')                                                                                      
#2 /var/www/html/controllers/Base.php(539): app\models\db\Consultation->getSettings()                                                                                                                       
#3 /var/www/html/controllers/Base.php(82): app\controllers\Base->loadConsultation('std', 'mv41')                                                                                                            
#4 /var/www/html/controllers/ConsultationController.php(45): app\controllers\Base->beforeAction(Object(yii\base\InlineAction))                                                                              
#5 /var/www/html/vendor/yiisoft/yii2/base/Controller.php(176): app\controllers\ConsultationController->beforeAction(Object(yii\base\InlineAction))                                                          
#6 /var/www/html/controllers/Base.php(148): yii\base\Controller->runAction('home', Array)                                                                                                                   
#7 /var/www/html/vendor/yiisoft/yii2/base/Module.php(552): app\controllers\Base->runAction('home', Array)                                                                                                   
#8 /var/www/html/vendor/yiisoft/yii2/web/Application.php(103): yii\base\Module->runAction('consultation/ho...', Array)                                                                                      
#9 /var/www/html/vendor/yiisoft/yii2/base/Application.php(384): yii\web\Application->handleRequest(Object(yii\web\Request))                                                                                 
#10 /var/www/html/web/index.php(52): yii\base\Application->run()
#11 {main} 
```

My fast-hacky-solution now was to remove the type cast in `models/settings/Consultation.php` for both of the variables ... eventually, you could also have a look onto that? =D

Thanks a lot!
Best
Martin

**Comment by macwinnie** [comment]
Hi @CatoTH,

I've done a fresh install and compared the config values in the `config.json` ... there were some new `null` values where in the early versions an empty srtring `""` was used (`domainSubdomain`, `lualatexPath`, ...)  and the `allowRegistration` setting was missing in the old one.

Adjusting those made the config work again as expected without manual changes in the files anymore – or did you change something in the background?

For me, that issue can be solved for that.

Best
Martin
