### ISSUE TITLE
TypeError bei Änderungsanträge übernehmen / einpflegen

### ISSUE THREAD

**Issue by melegiul** [CatoTH/antragsgruen#779]
Änderungsanträge übernehmen / einpflegen (merge) wirft einen error: `TypeError: Unsupported operand types: string + int`

Version: v4.11.1

```
2023-04-06 10:09:45 [][19914][2udbtoil0j79m1d5v3pjgdeibt][error][TypeError] TypeError: Unsupported operand types: string + int in models/db/IMotion.php:647
Stack trace:
#0 /var/www/models/db/Motion.php(400): app\models\db\IMotion::getNewTitlePrefixInternal()
#1 /var/www/views/amendment/_merge_step1.php(29): app\models\db\Motion->getNewTitlePrefix()
#2 /var/www/vendor/yiisoft/yii2/base/View.php(347): require('...')
#3 /var/www/vendor/yiisoft/yii2/base/View.php(257): yii\base\View->renderPhpFile()
#4 /var/www/vendor/yiisoft/yii2/base/View.php(156): yii\base\View->renderFile()
#5 /var/www/views/amendment/merge_with_collisions.php(69): yii\base\View->render()
#6 /var/www/vendor/yiisoft/yii2/base/View.php(347): require('...')
#7 /var/www/vendor/yiisoft/yii2/base/View.php(257): yii\base\View->renderPhpFile()
#8 /var/www/vendor/yiisoft/yii2/base/View.php(156): yii\base\View->renderFile()
#9 /var/www/vendor/yiisoft/yii2/base/Controller.php(407): yii\base\View->render()
#10 /var/www/controllers/Base.php(286): yii\base\Controller->render()
#11 /var/www/controllers/AmendmentMergingTrait.php(201): app\controllers\Base->render()
#12 [internal function]: app\controllers\AmendmentController->actionMerge()
#13 /var/www/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array()
#14 /var/www/vendor/yiisoft/yii2/base/Controller.php(178): yii\base\InlineAction->runWithParams()
#15 /var/www/controllers/Base.php(148): yii\base\Controller->runAction()
#16 /var/www/vendor/yiisoft/yii2/base/Module.php(552): app\controllers\Base->runAction()
#17 /var/www/vendor/yiisoft/yii2/web/Application.php(103): yii\base\Module->runAction()
#18 /var/www/vendor/yiisoft/yii2/base/Application.php(384): yii\web\Application->handleRequest()
#19 /var/w
```

**Comment by CatoTH** [comment]
Hi,
kannst du einmal schauen, was da in der Zeile 647 von models/db/IMotion.php bei euch steht? Weil in https://github.com/CatoTH/antragsgruen/blob/v4.11.1/models/db/IMotion.php#L647 (Version 4.11.1) ist das nur ein Kommentar, daher überrascht mir das etwas

**Comment by melegiul** [comment]
Hey, sorry ich habe mich wohl bei der Version geirrt. Ich dachte schon das wir die neueste Version hätten.

Im editor auf dem server habe ich vorhin in der Zeile 647 das hier gesehen: https://github.com/CatoTH/antragsgruen/blob/743c6d1f4c9ed379f34e3f9532acc7fc60622e3c/models/db/IMotion.php#L629

Wenn der Wert von `$last` nicht nummerisch ist, könnte er schon den TypeError ausgelöst haben.

Auf dem main branch sollte es schon gelöst sein, da gibt es an der Stelle noch einen cast.
https://github.com/CatoTH/antragsgruen/blob/1771af13aa563ff5f740855a26cef27bdf3e3e10/components/MotionNumbering.php#L18

**Comment by CatoTH** [comment]
Wie ist denn der genaue Antragspräfix bei euch? ich kann das jetzt spontan nicht reproduzieren, da das  `$last + 1` auch bei der alten Version nur greift, wenn $last > 0 ist...
Ansonsten: ist es eine Übergangslösung für euch, erst mal diesen Typecast mit einzubauen? Ich bin mir nicht sicher, ob sich speziell dafür jetzt ein eigenes Release lohnen würde.

**Comment by melegiul** [comment]
Das Antragspräfix für den problematischen Antrag heißt: `L1NEU eingefügt Ä1`.
Aber du hast Recht, die `$last > 0` Bedingungen sollte eigentlich schon reichen.
Danke dir, ich denke wir können das erstmal so lassen ohne Übergangslösung.
