### ISSUE TITLE
Migrations from Console not working

### ISSUE THREAD

**Issue by lukas-staab** [CatoTH/antragsgruen#783]
* I cannot update the database via console at update from 4.11.0 to 4.11.1 - web db migration works. Error: 
```
php8.0 yii migrate
Yii Migration Tool (based on Yii v2.0.47)

Exception 'yii\base\UnknownPropertyException' with message 'Getting unknown property: yii\console\controllers\MigrateController::layoutParams'
```

I installed via downloading the release. 

I also could not install the DB from a fresh install via console without webinstaller  (was earlier with 4.10.1, was probably the same error, felt to minor to report it there felt like fitting comment here)

**Comment by CatoTH** [comment]
So how did you update the code for the program, if not through the web updater? Did you download it through there and then use the migration from the command line?

My guess on this issue is that the database connection might not be configured correctly. I can only reproduce that error if I enter an invalid connection string in the config.json - then it tries to render an error page and breaks. If the database is correct in the first place, it shows me no available migrations...

**Comment by lukas-staab** [comment]
Ah now, sorry for the missunderstanding. I started the update procedure via web. Download and installation worked. Afterwards it tells me to do db migrations (it says preferred through commandline command I quoted) - that throws said error. If I use the web updater for the db migrations that worked (maybe that was db migration was a leftover from 4.10. to 4.11. and i did the fileupdates to fast?). Application and web updater works (before and after), so a config error is imo not the issue.

**Comment by lukas-staab** [comment]
Here you go: 

```
:~/antragsgruen-4.10.1$ php8.0 yii migrate
Yii Migration Tool (based on Yii v2.0.47)

SQLSTATE[HY000] [2002] No such file or directory
#0 ~/antragsgruen-4.10.1/components/yii/DBConnection.php(17): yii\db\Connection->open()
#1 ~/antragsgruen-4.10.1/vendor/yiisoft/yii2/db/Connection.php(1067): app\components\yii\DBConnection->open()
#2 ~/antragsgruen-4.10.1/vendor/yiisoft/yii2/db/Connection.php(1054): yii\db\Connection->getMasterPdo()
#3 ~/antragsgruen-4.10.1/vendor/yiisoft/yii2/db/Command.php(261): yii\db\Connection->getSlavePdo()
#4 ~/antragsgruen-4.10.1/vendor/yiisoft/yii2/db/Command.php(1163): yii\db\Command->prepare()
#5 ~/antragsgruen-4.10.1/vendor/yiisoft/yii2/db/Command.php(410): yii\db\Command->queryInternal()
#6 ~/antragsgruen-4.10.1/vendor/yiisoft/yii2/db/mysql/Schema.php(320): yii\db\Command->queryAll()
#7 ~/antragsgruen-4.10.1/vendor/yiisoft/yii2/db/mysql/Schema.php(125): yii\db\mysql\Schema->findColumns()
#8 ~/antragsgruen-4.10.1/vendor/yiisoft/yii2/db/Schema.php(756): yii\db\mysql\Schema->loadTableSchema()
#9 ~/antragsgruen-4.10.1/vendor/yiisoft/yii2/db/Schema.php(192): yii\db\Schema->getTableMetadata()
#10 ~/antragsgruen-4.10.1/vendor/yiisoft/yii2/console/controllers/MigrateController.php(211): yii\db\Schema->getTableSchema()
#11 ~/antragsgruen-4.10.1/vendor/yiisoft/yii2/console/controllers/BaseMigrateController.php(908): yii\console\controllers\MigrateController->getMigrationHistory()
#12 ~/antragsgruen-4.10.1/vendor/yiisoft/yii2/console/controllers/BaseMigrateController.php(183): yii\console\controllers\BaseMigrateController->getNewMigrations()
#13 [internal function]: yii\console\controllers\BaseMigrateController->actionUp()
#14 ~/antragsgruen-4.10.1/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array()
#15 ~/antragsgruen-4.10.1/vendor/yiisoft/yii2/base/Controller.php(178): yii\base\InlineAction->runWithParams()
#16 ~/antragsgruen-4.10.1/vendor/yiisoft/yii2/console/Controller.php(180): yii\base\Controller->runAction()
#17 ~/antragsgruen-4.10.1/vendor/yiisoft/yii2/base/Module.php(552): yii\console\Controller->runAction()
#18 ~/antragsgruen-4.10.1/vendor/yiisoft/yii2/console/Application.php(180): yii\base\Module->runAction()
#19 ~/antragsgruen-4.10.1/vendor/yiisoft/yii2/console/Application.php(147): yii\console\Application->runAction()
#20 ~/antragsgruen-4.10.1/vendor/yiisoft/yii2/base/Application.php(384): yii\console\Application->handleRequest()
#21 ~/antragsgruen-4.10.1/yii(23): yii\base\Application->run()
```
config.json
```
    "dbConnection": {
        "dsn": "mysql:host=;dbname=antragsgruen",
        "emulatePrepare": true,
        "username": "antragsgruen",
        "password": "XXX",
        "charset": "utf8mb4",
        "enableSchemaCache": true,
        "schemaCacheDuration": 3600,
        "schemaCache": "cache",
        "class": "app\\components\\yii\\DBConnection"
    },

```

**Comment by CatoTH** [comment]
I haven't really checked it through yet, but in your config.json it's a bit curious that `host=` is empty. Maybe is that supposed to be localhost or 127.0.0.1 or something like that? Not sure if this is related though...
