### ISSUE TITLE
Fehler 8192 nach Absenden von einem Antrag

### ISSUE THREAD

**Issue by noriakisana** [CatoTH/antragsgruen#801]
Hi,

wir haben bei uns die Instanz auf die neuste Version 4.11.1 hochgezogen und haben das Problem, dass jedes mal, wenn Antrag / Protokoll / Bericht usw. abgesendet wird, der eine Fehlerseite mit der Schrift Error #8192 kommt.

Die Sachen werden trotzdem gespeichert und angezeigt.

**Comment by CatoTH** [comment]
Hi,

ist das eine selbst gehostete Version, oder eine unter antragsgruen.de? Falls ersteres, kommt etwas in der runtime/logs/app.log?

**Comment by noriakisana** [comment]
Hi,

ist selbstgehostet,
das hier ist ein einzige Fehler der mir aufgefallen ist.

`2023-05-25 14:14:10 [46.114.210.15][43][0f3c549bad3865413da584f3ee6fdf1f][error][yii\base\ErrorException:8192] yii\base\ErrorException: urlencode(): Passing null to parameter #1 ($string) of type string is deprecated in /var/www/html/components/mail/SMTP.php:76
Stack trace:
#0 [internal function]: yii\base\ErrorHandler->handleError(8192, 'urlencode(): Pa...', '/var/www/html/c...', 76)
#1 /var/www/html/components/mail/SMTP.php(76): urlencode(NULL)
#2 /var/www/html/components/mail/Base.php(121): app\components\mail\SMTP->getTransport()
#3 /var/www/html/components/mail/Tools.php(102): app\components\mail\Base->send(Object(Symfony\Component\Mime\Email), 'stupa.stuve@uni...')
#4 /var/www/html/models/notifications/Base.php(37): app\components\mail\Tools::sendWithLog(3, Object(app\models\db\Consultation), 'stupa.stuve@uni...', NULL, 'Neuer Antrag', 'Es wurde ein ne...')
#5 /var/www/html/models/notifications/Base.php(63): app\models\notifications\Base->sendEmailAdmin()
#6 /var/www/html/models/notifications/MotionSubmitted.php(24): app\models\notifications\Base->send()
#7 /var/www/html/models/notifications/Base.php(19): app\models\notifications\MotionSubmitted->send()
#8 /var/www/html/models/notifications/MotionSubmitted.php(19): app\models\notifications\Base->__construct()
#9 /var/www/html/models/db/Motion.php(806): app\models\notifications\MotionSubmitted->__construct(Object(app\models\db\Motion))
#10 [internal function]: app\models\db\Motion->setInitialSubmitted(Object(app\models\events\MotionEvent))
#11 /var/www/html/vendor/yiisoft/yii2/base/Component.php(633): call_user_func(Array, Object(app\models\events\MotionEvent))
#12 /var/www/html/controllers/MotionController.php(203): yii\base\Component->trigger('submitted', Object(app\models\events\MotionEvent))
#13 [internal function]: app\controllers\MotionController->actionCreateconfirm('Bericht-aus-dem...', 'create')
#14 /var/www/html/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#15 /var/www/html/vendor/yiisoft/yii2/base/Controller.php(178): yii\base\InlineAction->runWithParams(Array)
#16 /var/www/html/controllers/Base.php(142): yii\base\Controller->runAction('createconfirm', Array)
#17 /var/www/html/vendor/yiisoft/yii2/base/Module.php(552): app\controllers\Base->runAction('createconfirm', Array)
#18 /var/www/html/vendor/yiisoft/yii2/web/Application.php(103): yii\base\Module->runAction('motion/createco...', Array)
#19 /var/www/html/vendor/yiisoft/yii2/base/Application.php(384): yii\web\Application->handleRequest(Object(yii\web\Request))
#20 /var/www/html/web/index.php(22): yii\base\Application->run()
#21 {main}`

**Comment by noriakisana** [comment]
Hi @CatoTH irgendeine Idee woran es liegen könnte? ich denke mal, es hat was mit der Bestätigungsmail zu tun, weiß aber nicht, wie ich es fixen kann
