### ISSUE TITLE
Error nach Installation

### ISSUE THREAD

**Issue by ben-biber** [CatoTH/antragsgruen#855]
Hier die URL: https://antragsgruen.kjg-dossenheim.org
Nach der Installation via Docker bekomme ich leider nur diese Fehlermeldung

```
2023-11-05 13:37:38 [172.71.102.220][-][18ca6524ed27cb8dadcc35e162537caa][error][yii\db\Exception] PDOException: SQLSTATE[HY000]: General error: 1364 Field 'id' doesn't have a default value in /var/www/html/vendor/yiisoft/yii2/db/Command.php:1302
Stack trace:
#0 /var/www/html/vendor/yiisoft/yii2/db/Command.php(1302): PDOStatement->execute()
#1 /var/www/html/vendor/yiisoft/yii2/db/Command.php(1102): yii\db\Command->internalExecute('INSERT INTO `us...')
#2 /var/www/html/vendor/yiisoft/yii2/db/Schema.php(431): yii\db\Command->execute()
#3 /var/www/html/vendor/yiisoft/yii2/db/ActiveRecord.php(604): yii\db\Schema->insert('user', Array)
#4 /var/www/html/vendor/yiisoft/yii2/db/ActiveRecord.php(570): yii\db\ActiveRecord->insertInternal(NULL)
#5 /var/www/html/vendor/yiisoft/yii2/db/BaseActiveRecord.php(676): yii\db\ActiveRecord->insert(true, NULL)
#6 /var/www/html/models/forms/AntragsgruenInitDb.php(308): yii\db\BaseActiveRecord->save()
#7 /var/www/html/models/forms/AntragsgruenInitDb.php(294): app\models\forms\AntragsgruenInitDb->createAdminAccount()
#8 /var/www/html/controllers/InstallationController.php(166): app\models\forms\AntragsgruenInitDb->createOrUpdateAdminAccount()
#9 [internal function]: app\controllers\InstallationController->actionIndex('en')
#10 /var/www/html/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#11 /var/www/html/vendor/yiisoft/yii2/base/Controller.php(178): yii\base\InlineAction->runWithParams(Array)
#12 /var/www/html/controllers/Base.php(148): yii\base\Controller->runAction('index', Array)
#13 /var/www/html/vendor/yiisoft/yii2/base/Module.php(552): app\controllers\Base->runAction('index', Array)
#14 /var/www/html/vendor/yiisoft/yii2/web/Application.php(103): yii\base\Module->runAction('', Array)
#15 /var/www/html/vendor/yiisoft/yii2/base/Application.php(384): yii\web\Application->handleRequest(Object(yii\web\Request))
#16 /var/www/html/web/index.php(52): yii\base\Application->run()
#17 {main}

Next yii\db\Exception: SQLSTATE[HY000]: General error: 1364 Field 'id' doesn't have a default value
The SQL being executed was: INSERT INTO `user` (`auth`, `status`, `email`, `emailConfirmed`, `pwdEnc`, `name`, `organizationIds`, `authKey`, `dateCreation`) VALUES ('email:xxxxxxx@xxxxxxx.org', 0, 'xxxxxxx@xxxxxxx.org', 1, 'xxxxxxx', '', '', 'xxxxxxx', NOW()) in /var/www/html/vendor/yiisoft/yii2/db/Schema.php:676
Stack trace:
#0 /var/www/html/vendor/yiisoft/yii2/db/Command.php(1307): yii\db\Schema->convertException(Object(PDOException), 'INSERT INTO `us...')
#1 /var/www/html/vendor/yiisoft/yii2/db/Command.php(1102): yii\db\Command->internalExecute('INSERT INTO `us...')
#2 /var/www/html/vendor/yiisoft/yii2/db/Schema.php(431): yii\db\Command->execute()
#3 /var/www/html/vendor/yiisoft/yii2/db/ActiveRecord.php(604): yii\db\Schema->insert('user', Array)
#4 /var/www/html/vendor/yiisoft/yii2/db/ActiveRecord.php(570): yii\db\ActiveRecord->insertInternal(NULL)
#5 /var/www/html/vendor/yiisoft/yii2/db/BaseActiveRecord.php(676): yii\db\ActiveRecord->insert(true, NULL)
#6 /var/www/html/models/forms/AntragsgruenInitDb.php(308): yii\db\BaseActiveRecord->save()
#7 /var/www/html/models/forms/AntragsgruenInitDb.php(294): app\models\forms\AntragsgruenInitDb->createAdminAccount()
#8 /var/www/html/controllers/InstallationController.php(166): app\models\forms\AntragsgruenInitDb->createOrUpdateAdminAccount()
#9 [internal function]: app\controllers\InstallationController->actionIndex('en')
#10 /var/www/html/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#11 /var/www/html/vendor/yiisoft/yii2/base/Controller.php(178): yii\base\InlineAction->runWithParams(Array)
#12 /var/www/html/controllers/Base.php(148): yii\base\Controller->runAction('index', Array)
#13 /var/www/html/vendor/yiisoft/yii2/base/Module.php(552): app\controllers\Base->runAction('index', Array)
#14 /var/www/html/vendor/yiisoft/yii2/web/Application.php(103): yii\base\Module->runAction('', Array)
#15 /var/www/html/vendor/yiisoft/yii2/base/Application.php(384): yii\web\Application->handleRequest(Object(yii\web\Request))
#16 /var/www/html/web/index.php(52): yii\base\Application->run()
#17 {main}
Additional Information:
Array
(
    [0] => HY000
    [1] => 1364
    [2] => Field 'id' doesn't have a default value
)
```

**Comment by CatoTH** [comment]
Hallo, das klingt danach als wäre die Datenbank nicht korrekt initialisiert worden - konkret mindestens https://github.com/CatoTH/antragsgruen/blob/main/assets/db/create.sql#L1288 dürfte nicht mehr ausgeführt worden sein. Ohne Datenbankzugriff kann ich das leider nicht genauer einschränken, du könntest aber z.B. einmal ausprobieren in der verlinkten Datei alls Vorkommnisse von ###TABLE_PREFIX### zu entfernen und dann das Skript von Hand in einer leeren Datenbank auszuführen, ob das dann funktioniert.
